# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /register:
    post:
      summary: This is an endpoint for user registration
      operationId: register
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
      responses:
        '200':
          description: registration succeed
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MessageResponse"
        '400':
          description: registration failed
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MessageResponse"
        '500':
          description: registration failed - internal server error
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MessageResponse"
components:
  schemas:
    UserRegistrationRequest:
      type: object
      required: 
        - username
        - password
      properties:
        username:
          description: username of the user
          type: string
        password:
          description: password of the user
          type: string
    MessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
